### PR TITLE
Add custom details field to the incident trigger/step

### PR DESCRIPTION
**Pull request by petgoldfish**
### Problem
In v0.6.0 the Pagerduty client [was bumped to v3.0](https://github.com/alexanderlz/jenkins-pagerduty-plugin/commit/f61eb3b6aefaf3539d49c88df5870369a09b8b2c), causing a breaking change in field names such as `incDetails`/`incDescription` -> `incidentSummary`. Further, the support for specifying custom details was dropped, because the new Pagerduty client version expects a `JSONObject` as opposed to a `String`.

This behavior is detailed in #50 

### Solution
This PR adds support for specifying custom details again.

In the pipeline step, specify custom details as a `Map`:
```
pagerduty routingKey: XX, ... , customDetails: [key1: "value1", ... , keyN: "value2"]
```

In the trigger UI, specify the custom details as a `JSON` string:
(Updated `screen2.png`)

screen2

### Motivation
As seen in #50, a lot of us want to pass in custom details to the pagerduty page.

Please let me know if I need to change anything. Cheers!

### CODE REVIEW

**Comment by alexanderlz** [comment]
hi @petgoldfish 

first I would like to thank you for the PR!
I have some (yet) uncommitted code that handles the custom details, I released it internally to couple of guys to help me testing it some time ago.
I will try to free some time (hopefully in the upcoming week) to finalize that and commit -> and then I'll be able to properly inspect your PR

Thanks again!

**Comment by alexanderlz** [comment]
@petgoldfish  - if you wish you can give me a hand testing this hpi
https://github.com/alexanderlz/jenkins-pagerduty-plugin/blob/alexanderlz-patch-1/pagerduty.hpi

**Comment by petgoldfish** [comment]
Sorry, only just got around back to this again. I'll try to test that hpi as much as I can.
Thanks!

**Comment by petgoldfish** [comment]
@alexanderlz I was wondering if you had a chance to look over the PR again?

**Comment by alexanderlz** [comment]
@petgoldfish  - sorry for the delay.

me and couple of my friends are finalizing some tests to the new plugin version, hopefully by next weekend it's rolled to update center

**Comment by ron-matsliah** [comment]
Hi @alexanderlz any news? this feature will really help us :)

**Comment by roman-batrak-sp** [comment]
year has passed. any updates ?

**Comment by alexanderlz** [comment]
@petgoldfish  @ron-matsliah  @roman-batrak-sp 

merged (took a lot of time, I know, and really sorry for that)
in testing phase, will roll to UpdateCenter as soon as I can.

**Comment by hoshsadiq** [comment]
@alexanderlz any update on rolling this out to UpdateCenter?

**Pull request merged**
